"""
Pydantic models for the Autonomous Night Watch system.

These models define the data structures for the overnight agent orchestration,
including missions, task queues, and execution results.
"""

from datetime import UTC, datetime
from enum import Enum

from pydantic import BaseModel, Field


class TaskStatus(str, Enum):
    """Status of a task in the queue."""

    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    CONFLICT = "conflict"
    TIMEOUT = "timeout"


class MissionPriority(int, Enum):
    """Priority levels for missions."""

    CRITICAL = 1  # Must complete tonight
    HIGH = 2  # Should complete if time allows
    MEDIUM = 3  # Nice to have
    LOW = 4  # Only if all higher priority tasks done


class Mission(BaseModel):
    """A mission to be executed by the night watch.

    Missions are loaded from overnight_missions.json and converted to TaskQueueItems.
    """

    id: str = Field(..., description="Unique mission identifier (e.g., 'pydantic_migration')")
    title: str = Field(..., description="Human-readable mission title")
    description: str = Field(..., description="Detailed mission description")
    command: str = Field(
        ..., description="/primeA command to execute (e.g., '/primeA \"Migrate Dict[Any, Any]\"')"
    )
    priority: MissionPriority = Field(
        default=MissionPriority.MEDIUM, description="Mission priority level"
    )
    estimated_duration_minutes: int = Field(
        ..., gt=0, description="Estimated completion time in minutes"
    )
    tags: list[str] = Field(default_factory=list, description="Tags for categorization")
    enabled: bool = Field(default=True, description="Whether mission is enabled")


class TaskQueueItem(BaseModel):
    """A task in the execution queue.

    Created from a Mission when the orchestrator initializes the queue.
    """

    id: str = Field(..., description="Unique task ID (e.g., 'task_001')")
    mission_id: str = Field(..., description="Reference to source Mission.id")
    title: str = Field(..., description="Task title")
    command: str = Field(..., description="/primeA command to execute")
    priority: int = Field(..., description="Numeric priority (1 = highest)")
    estimated_duration_minutes: int = Field(..., description="Estimated completion time")
    status: TaskStatus = Field(default=TaskStatus.PENDING, description="Current task status")
    assigned_to: str | None = Field(
        None, description="Worker ID that claimed this task (e.g., 'worker-m4pro-01')"
    )
    branch_name: str | None = Field(
        None,
        description="Git branch name created for this task (e.g., 'night-watch/pydantic-migration-20251012-0315')",
    )
    started_at: datetime | None = Field(None, description="ISO timestamp when task started")
    completed_at: datetime | None = Field(None, description="ISO timestamp when task completed")
    error_message: str | None = Field(None, description="Error message if task failed")
    retry_count: int = Field(default=0, description="Number of retry attempts")


class TaskQueue(BaseModel):
    """The central task queue shared between orchestrator and workers.

    Stored as task_queue.json with atomic updates via file locking.
    """

    version: str = Field(default="1.0", description="Queue format version")
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC), description="Queue creation timestamp"
    )
    mission_set: str = Field(..., description="Mission set name (e.g., 'full', 'testing')")
    tasks: list[TaskQueueItem] = Field(default_factory=list, description="List of tasks")


class MissionResult(BaseModel):
    """Result of a completed mission execution.

    Generated by workers and aggregated by orchestrator for final report.
    """

    task_id: str = Field(..., description="Task ID")
    mission_id: str = Field(..., description="Mission ID")
    title: str = Field(..., description="Mission title")
    status: TaskStatus = Field(..., description="Final status")
    worker_id: str = Field(..., description="Worker that executed this mission")
    branch_name: str | None = Field(None, description="Git branch name")
    started_at: datetime = Field(..., description="Start timestamp")
    completed_at: datetime = Field(..., description="Completion timestamp")
    duration_minutes: float = Field(..., description="Execution duration in minutes")
    tests_passed: bool = Field(default=False, description="Whether all tests passed")
    pr_url: str | None = Field(None, description="Pull request URL if auto-created")
    error_message: str | None = Field(None, description="Error message if failed")
    log_file: str = Field(..., description="Path to detailed execution log")


class OrchestratorConfig(BaseModel):
    """Configuration for the overnight orchestrator.

    Passed via command-line arguments to /start-overnight-agents.
    """

    pro_threads: int = Field(
        default=2, ge=1, le=10, description="Number of worker threads on M4 Pro"
    )
    air_threads: int = Field(
        default=1, ge=0, le=5, description="Number of worker threads on M4 Air"
    )
    mission_set: str = Field(
        default="full",
        description="Mission set to execute ('refactoring', 'testing', 'docs', 'full')",
    )
    max_task_duration_minutes: int = Field(
        default=60, ge=10, description="Maximum time per task before timeout"
    )
    enable_auto_pr: bool = Field(
        default=False, description="Automatically create PRs for completed tasks"
    )
    dry_run: bool = Field(default=False, description="Simulate execution without making changes")


class OrchestratorReport(BaseModel):
    """Final report generated by orchestrator after all workers complete.

    Displayed to user in the morning with summary of overnight activity.
    """

    orchestrator_started_at: datetime = Field(..., description="Orchestrator start time")
    orchestrator_completed_at: datetime = Field(..., description="Orchestrator end time")
    total_duration_minutes: float = Field(..., description="Total execution time")
    mission_set: str = Field(..., description="Mission set executed")
    total_tasks: int = Field(..., description="Total tasks in queue")
    completed_tasks: int = Field(..., description="Successfully completed tasks")
    failed_tasks: int = Field(..., description="Failed tasks")
    conflict_tasks: int = Field(..., description="Tasks with git conflicts")
    timeout_tasks: int = Field(..., description="Tasks that timed out")
    results: list[MissionResult] = Field(default_factory=list, description="Detailed results")
    branches_created: list[str] = Field(
        default_factory=list, description="All git branches created"
    )
    next_steps: list[str] = Field(
        default_factory=list,
        description="Recommended next steps for user (e.g., review PRs, merge branches)",
    )
