name: Constitutional CI/CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  constitutional-compliance:
    name: Article II - 100% Verification
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          # Install ALL requirements first (includes all dependencies)
          pip install -r requirements.txt
          # Then install package in editable mode (no dependencies, already installed)
          pip install -e . --no-deps

      - name: Run constitutional validation
        run: |
          # Article I: Complete context - run ALL tests
          python run_tests.py --run-all
        env:
          SKIP_SPEC_TRACEABILITY: "true"
          FORCE_RUN_ALL_TESTS: "1"

      - name: Verify 100% pass rate
        if: failure()
        run: |
          echo "❌ BLOCKED by Constitution Article II"
          echo "100% test success required - no exceptions"
          exit 1

  health-check:
    name: System Health Validation
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install -e . --no-deps

      - name: Run health check
        run: |
          chmod +x scripts/health_check.sh
          SKIP_SPEC_TRACEABILITY=true ./scripts/health_check.sh

  quality-gates:
    name: Article III - Quality Enforcement
    runs-on: ubuntu-latest
    needs: [constitutional-compliance, health-check]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate constitutional compliance
        run: |
          echo "✅ All quality gates passed"
          echo "✅ Article I: Complete Context"
          echo "✅ Article II: 100% Verification"
          echo "✅ Article III: Automated Enforcement"
